name: Continuous Integration

on: [push, pull_request]

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10

    - name: Install Dependencies
      run: npm install
      
    - name: Test
      run: react-scripts test
      
    - name: Build
      run: react-scripts build
