name: CI

on: [push, pull_request]

jobs:
  installAndTest:
    name: Install and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10

      - name: Install Dependencies
        run: npm install

      - name: Test
        run: npm test
